pretzel: 
engine: liquid
paginate: 4
paginate_path: /page/:num/
name: robertbird
permalink: /:categories/:title
exclude: ['node_modules', 'grunt-tasks']
gems: [jekyll-paginate]
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      sitetitle: "test"